apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: product-owner-binding
subjects:
  - kind: User
    name: productowner
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: product-owner-role
  apiGroup: rbac.authorization.k8s.io